/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface;

import BusinessLogic.FieldLevelValidation;
import BusinessLogic.Patient;
import BusinessLogic.Person;
import BusinessLogic.PersonDirectory;
import BusinessLogic.VitalSign;
import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author Piyush
 */
public class ViewVitalSignDetailsJPanel extends javax.swing.JPanel {

    private PersonDirectory personDirectory;
    private JPanel userProcessContainer;
    private Patient patient;
    private Person person;
    private VitalSign vs;
    private ManagePersonJPanel managePersonJPanel;
    private ViewPersonDetailsJPanel vpdj;
    private ManagePatientJPanel mpjp;
    
    public ViewVitalSignDetailsJPanel(Person person, Patient patient, JPanel userProcessContainer, VitalSign vs, ViewPersonDetailsJPanel vpdj) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.personDirectory = personDirectory;
        person = new Person();
        this.patient = patient;
        this.vpdj = vpdj;
        this.vs = vs;
        populateFields();
    }
    
    public ViewVitalSignDetailsJPanel(Person person, Patient patient, JPanel userProcessContainer, VitalSign vs, ManagePatientJPanel mpjp) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.personDirectory = personDirectory;
        person = new Person();
        this.patient = patient;
        this.mpjp = mpjp;
        this.vs = vs;
        populateFields();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        respiratoryRateTxtField = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        heartRateTxtField = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        bloodPressureTxtFiled = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        weightTxtField = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        patientIDTxtField = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        timestampTxtField = new javax.swing.JTextField();
        updateBtn = new javax.swing.JButton();
        saveBtn = new javax.swing.JButton();
        backBtn = new javax.swing.JButton();

        jLabel1.setText("Respiratory Rate");

        respiratoryRateTxtField.setEditable(false);

        jLabel2.setText("Heart Rate");

        heartRateTxtField.setEditable(false);

        jLabel3.setText("Symbollic Blood Pressure");

        bloodPressureTxtFiled.setEditable(false);

        jLabel4.setText("Weight in Pounds");

        weightTxtField.setEditable(false);

        jLabel9.setText("Patient ID");

        patientIDTxtField.setEditable(false);
        patientIDTxtField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                patientIDTxtFieldActionPerformed(evt);
            }
        });

        jLabel10.setText("Timestamp");

        timestampTxtField.setEditable(false);

        updateBtn.setText("Update");
        updateBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateBtnActionPerformed(evt);
            }
        });

        saveBtn.setText("Save");
        saveBtn.setEnabled(false);
        saveBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveBtnActionPerformed(evt);
            }
        });

        backBtn.setText("<< Back");
        backBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(heartRateTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel9))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 227, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(respiratoryRateTxtField)
                    .addComponent(patientIDTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(jLabel10))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(weightTxtField)
                    .addComponent(timestampTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)))
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(bloodPressureTxtFiled, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                    .addGap(82, 82, 82)
                    .addComponent(saveBtn)
                    .addGap(27, 27, 27)
                    .addComponent(updateBtn)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGroup(layout.createSequentialGroup()
                    .addGap(56, 56, 56)
                    .addComponent(backBtn)
                    .addContainerGap(292, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(patientIDTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(respiratoryRateTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(heartRateTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(bloodPressureTxtFiled, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(weightTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel10)
                    .addComponent(timestampTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(updateBtn)
                    .addComponent(saveBtn))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(backBtn)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void patientIDTxtFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_patientIDTxtFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_patientIDTxtFieldActionPerformed

    private void backBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backBtnActionPerformed
    userProcessContainer.remove(this);
    mpjp.populateTable();
    CardLayout layout = (CardLayout)userProcessContainer.getLayout();
    layout.previous(userProcessContainer);
    }//GEN-LAST:event_backBtnActionPerformed

    private void updateBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateBtnActionPerformed
    respiratoryRateTxtField.setEditable(true);
    heartRateTxtField.setEditable(true);
    bloodPressureTxtFiled.setEditable(true);
    weightTxtField.setEditable(true);
    updateBtn.setEnabled(false);
    saveBtn.setEnabled(true);
    }//GEN-LAST:event_updateBtnActionPerformed

    private void saveBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveBtnActionPerformed
   
    FieldLevelValidation fieldLevelValidation = new FieldLevelValidation();
    
    int counter = 0;
    if(respiratoryRateTxtField.getText().trim().isEmpty()||
                heartRateTxtField.getText().trim().isEmpty()||
                    bloodPressureTxtFiled.getText().trim().isEmpty()||
                        weightTxtField.getText().trim().isEmpty())
    {
        JOptionPane.showMessageDialog(null, "One or More Fields are Blank!");
    }
    else{
    
    String respiratoryRate = respiratoryRateTxtField.getText().trim();
    boolean isRespiratoryRateValid = fieldLevelValidation.checkPatientIDField(respiratoryRate);
    if(isRespiratoryRateValid==true)
    {
        counter++;
    }
    else
        JOptionPane.showMessageDialog(null, "Patient Respiratory Rate Invalid");
    
    String heartRate = heartRateTxtField.getText().trim();
    boolean isHeartRateValid = fieldLevelValidation.checkPatientIDField(heartRate);
    if(isHeartRateValid==true)
    {
        counter++;
    }
    else
        JOptionPane.showMessageDialog(null, "Patient Heart Rate Invalid");
    
    String bloodPressure = bloodPressureTxtFiled.getText().trim();
    boolean isBloodPressureValid = fieldLevelValidation.checkPatientIDField(bloodPressure);
    if(isBloodPressureValid==true)
    {
        counter++;
    }
    else
        JOptionPane.showMessageDialog(null, "Patient Blood Pressure Invalid");
    
    String weightInPounds = weightTxtField.getText().trim();
    boolean isWeightInPoundsValid = fieldLevelValidation.checkPatientIDField(weightInPounds);
    if(isWeightInPoundsValid==true)
    {
        counter++;
    }
    else
        JOptionPane.showMessageDialog(null, "Patient Weight In Pounds Invalid");
    }
    if(counter==4){    
        
    vs.setHeartRate(Integer.parseInt(heartRateTxtField.getText()));
    vs.setRespiratoryRate(Integer.parseInt(respiratoryRateTxtField.getText()));
    vs.setSymbolicBloodPressure(Integer.parseInt(bloodPressureTxtFiled.getText()));
    vs.setWeightInpounds(Float.parseFloat(weightTxtField.getText()));
    JOptionPane.showMessageDialog(null, "Patient Profile Updated SSuccessfully");
    saveBtn.setEnabled(false);
    updateBtn.setEnabled(true);
    respiratoryRateTxtField.setEditable(false);
    heartRateTxtField.setEditable(false);
    bloodPressureTxtFiled.setEditable(false);
    weightTxtField.setEditable(false);
    }
    }//GEN-LAST:event_saveBtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backBtn;
    private javax.swing.JTextField bloodPressureTxtFiled;
    private javax.swing.JTextField heartRateTxtField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField patientIDTxtField;
    private javax.swing.JTextField respiratoryRateTxtField;
    private javax.swing.JButton saveBtn;
    private javax.swing.JTextField timestampTxtField;
    private javax.swing.JButton updateBtn;
    private javax.swing.JTextField weightTxtField;
    // End of variables declaration//GEN-END:variables

    private void populateFields() {
    
    patientIDTxtField.setText(String.valueOf(vs));
    respiratoryRateTxtField.setText(String.valueOf(vs.getRespiratoryRate()));
    heartRateTxtField.setText(String.valueOf(vs.getHeartRate()));
    bloodPressureTxtFiled.setText(String.valueOf(vs.getSymbolicBloodPressure()));
    weightTxtField.setText(String.valueOf(vs.getWeightInpounds()));
    timestampTxtField.setText(String.valueOf(vs.getDateTimeStamp()));
    }

    }

