/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface;

import BusinessLogic.FieldLevelValidation;
import BusinessLogic.VitalSign;
import BusinessLogic.VitalSignHistory;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JOptionPane;

/**
 *
 * @author Piyush
 */
public class CreateVitalSign extends javax.swing.JPanel {

    /**
     * Creates new form CreatePatient
     */
    private VitalSignHistory vitalSignHistory;
    public CreateVitalSign(VitalSignHistory vitalSignHistory) {
        initComponents();
        this.vitalSignHistory = vitalSignHistory;
        SimpleDateFormat localDateFormat = new SimpleDateFormat("yyyy-MM-dd HH:mm:ss");
        timestampTxtField.setText(localDateFormat.format( new Date()));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        respiratoryRateTxtField = new javax.swing.JTextField();
        heartRateTxtField = new javax.swing.JTextField();
        bloodPressureTxtFiled = new javax.swing.JTextField();
        weightTxtField = new javax.swing.JTextField();
        timestampTxtField = new javax.swing.JTextField();
        createVitalSignBtn = new javax.swing.JButton();

        jLabel1.setText("Respiratory Rate");

        jLabel2.setText("Heart Rate");

        jLabel3.setText("Symbollic Blood Pressure");

        jLabel4.setText("Weight in Pounds");

        jLabel5.setText("Timestamp");

        timestampTxtField.setEditable(false);

        createVitalSignBtn.setText("Create Vital Sign");
        createVitalSignBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createVitalSignBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addGap(238, 238, 238)
                                .addComponent(timestampTxtField))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(weightTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(bloodPressureTxtFiled, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(heartRateTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(207, 207, 207)
                                .addComponent(respiratoryRateTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(176, 176, 176)
                        .addComponent(createVitalSignBtn)))
                .addGap(27, 27, 27))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(respiratoryRateTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(heartRateTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(bloodPressureTxtFiled, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(weightTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(timestampTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(createVitalSignBtn)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void createVitalSignBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createVitalSignBtnActionPerformed
    VitalSign vitalSign = vitalSignHistory.addVitalSign();

    String dateTimeStamp = timestampTxtField.getText().trim();
    FieldLevelValidation fieldLevelValidation = new FieldLevelValidation();
    if(respiratoryRateTxtField.getText().trim().isEmpty()||
            heartRateTxtField.getText().trim().isEmpty()||
                bloodPressureTxtFiled.getText().trim().isEmpty()||
                    weightTxtField.getText().trim().isEmpty())
    {
        JOptionPane.showMessageDialog(null, "One or More Fields are Blank!");
    }
    else{
        int counter = 0;
        String respiratoryRate = respiratoryRateTxtField.getText().trim();
    boolean isRespiratoryRateValid = fieldLevelValidation.checkRespiratoryRate(respiratoryRate);
    if(isRespiratoryRateValid==true)
    {
        vitalSign.setRespiratoryRate(Integer.parseInt(respiratoryRate));
        counter++;
    }
    else
        JOptionPane.showMessageDialog(null, "Respiratory Rate Invalid");
    
        String heartRate = heartRateTxtField.getText().trim();
        boolean isHeartRateValid = fieldLevelValidation.checkHeartRate(heartRate);
    if(isHeartRateValid==true)
    {
        vitalSign.setHeartRate(Integer.parseInt(heartRate));
        counter++;
    }
    else
        JOptionPane.showMessageDialog(null, "Heart Rate Invalid");
    
        String bloodPressure = bloodPressureTxtFiled.getText().trim();
        boolean isBloodPressureValid = fieldLevelValidation.checkBloodPressure(bloodPressure);
    if(isBloodPressureValid==true)
    {
        vitalSign.setSymbolicBloodPressure(Integer.parseInt(bloodPressure));
        counter++;
    }
    else
        JOptionPane.showMessageDialog(null, "Blood Pressure Invalid");
   
        String weightInPounds = weightTxtField.getText().trim();
        boolean isWeightInPoundsValid = fieldLevelValidation.checkWeightInPounds(weightInPounds);
    if(isWeightInPoundsValid==true)
    {
        vitalSign.setWeightInpounds(Float.parseFloat(weightInPounds));
        counter++;
    }
    else
        JOptionPane.showMessageDialog(null, "Weight in Pounds Invalid");
    
    vitalSign.setDateTimeStamp(dateTimeStamp);
    if(counter == 4)
    {
    JOptionPane.showMessageDialog(null, "Vital Sign Created Successfully!");
    resetFields();
    }
    }
    }//GEN-LAST:event_createVitalSignBtnActionPerformed

    private void resetFields() {
        respiratoryRateTxtField.setText("");
        heartRateTxtField.setText("");
        bloodPressureTxtFiled.setText("");
        weightTxtField.setText("");
        SimpleDateFormat localDateFormat = new SimpleDateFormat("yyyy-MM-dd HH:mm:ss");
        timestampTxtField.setText(localDateFormat.format( new Date()));
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField bloodPressureTxtFiled;
    private javax.swing.JButton createVitalSignBtn;
    private javax.swing.JTextField heartRateTxtField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JTextField respiratoryRateTxtField;
    private javax.swing.JTextField timestampTxtField;
    private javax.swing.JTextField weightTxtField;
    // End of variables declaration//GEN-END:variables
}
