/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface;

import BusinessLogic.Patient;
import BusinessLogic.VerifyLevel;
import BusinessLogic.VitalSign;
import BusinessLogic.VitalSignHistory;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Piyush
 */
public class ViewVitalSign extends javax.swing.JPanel {

    /**
     * Creates new form ViewVitalSign
     */
    private VitalSignHistory vitalSignHistory;
    private Patient patient;
    public ViewVitalSign(VitalSignHistory vitalSignHistory,Patient patient) {
        initComponents();
        this.vitalSignHistory = vitalSignHistory;
        this.patient = patient;
        displayTable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        VitalSignTable = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        respiratoryRateTxtField = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        heartRateTxtField = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        bloodPressureTxtFiled = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        weightTxtField = new javax.swing.JTextField();
        viewEntryBtn = new javax.swing.JButton();
        deleteEntryBtn = new javax.swing.JButton();

        VitalSignTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "TimeStamp", "Level"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(VitalSignTable);

        jLabel1.setText("Respiratory Rate");

        jLabel2.setText("Heart Rate");

        jLabel3.setText("Symbollic Blood Pressure");

        jLabel4.setText("Weight in Pounds");

        viewEntryBtn.setText("View");
        viewEntryBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewEntryBtnActionPerformed(evt);
            }
        });

        deleteEntryBtn.setText("Delete");
        deleteEntryBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteEntryBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(heartRateTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(weightTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel1)
                                        .addGap(207, 207, 207)
                                        .addComponent(respiratoryRateTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(9, 9, 9)
                                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 375, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(viewEntryBtn)
                            .addComponent(jLabel3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(bloodPressureTxtFiled, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap())
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(deleteEntryBtn)
                                .addGap(85, 85, 85))))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(respiratoryRateTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(23, 23, 23)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(bloodPressureTxtFiled, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(heartRateTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(38, 38, 38)))
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(weightTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(41, 41, 41)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(viewEntryBtn)
                    .addComponent(deleteEntryBtn))
                .addGap(33, 33, 33))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void viewEntryBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewEntryBtnActionPerformed
    int selectedRow = VitalSignTable.getSelectedRow();
    if(selectedRow>=0){
        VitalSign vs=(VitalSign)VitalSignTable.getValueAt(selectedRow,0);
        respiratoryRateTxtField.setText(String.valueOf(vs.getRespiratoryRate()));
        heartRateTxtField.setText(String.valueOf(vs.getHeartRate()));
        bloodPressureTxtFiled.setText(String.valueOf(vs.getSymbolicBloodPressure()));
        weightTxtField.setText(String.valueOf(vs.getWeightInpounds()));
    }
    else{
        JOptionPane.showMessageDialog(null, "Please Select a Row from the Table first","Warning",JOptionPane.WARNING_MESSAGE    );
    }
        
    }//GEN-LAST:event_viewEntryBtnActionPerformed

    private void deleteEntryBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteEntryBtnActionPerformed
        int selectedRow = VitalSignTable.getSelectedRow();
    if(selectedRow >= 0)
    {
        int dialogButton = JOptionPane.YES_NO_OPTION;
        int dialogResult = JOptionPane.showConfirmDialog(null, "Would You Like to Delete Vital Sign?", "Warning", dialogButton);
       if(dialogResult == JOptionPane.YES_OPTION){
        VitalSign vs = (VitalSign)VitalSignTable.getValueAt(selectedRow, 0);
        vitalSignHistory.deleteVitalSign(vs);
        displayTable();
        resetFields();
    }
    }
    else{
        JOptionPane.showMessageDialog(null, "Please Select a Row from the Table first","Warning",JOptionPane.WARNING_MESSAGE    );
    }
    }//GEN-LAST:event_deleteEntryBtnActionPerformed

    void displayTable()
    {
        DefaultTableModel dtm = (DefaultTableModel)VitalSignTable.getModel();    
    dtm.setRowCount(0);
    for(VitalSign vs : vitalSignHistory.getVitalSignHistory())
    {
        Object row[] = new Object[2];
        row[0]=vs;
        VerifyLevel verifyLevel = new VerifyLevel(vs,patient);
        row[1]=verifyLevel.verifyLevelNormalOrAbnormal();
        dtm.addRow(row);
    }
    }
    private void resetFields() {
        respiratoryRateTxtField.setText("");
        heartRateTxtField.setText("");
        bloodPressureTxtFiled.setText("");
        weightTxtField.setText("");
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable VitalSignTable;
    private javax.swing.JTextField bloodPressureTxtFiled;
    private javax.swing.JButton deleteEntryBtn;
    private javax.swing.JTextField heartRateTxtField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField respiratoryRateTxtField;
    private javax.swing.JButton viewEntryBtn;
    private javax.swing.JTextField weightTxtField;
    // End of variables declaration//GEN-END:variables
}
