/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.Reporting;

import Business.Customer;
import Business.CustomerCatalog;
import Business.MasterOrderCatalog;
import Business.Order;
import Business.OrderItem;
import Business.SalesPerson;
import Business.SalesPersonDirectory;
import Business.SupplierDirectory;
import java.util.ArrayList;
import java.util.Collections;
import javax.swing.JPanel;

/**
 *
 * @author Piyush
 */
public class Reporting extends javax.swing.JPanel {

    private JPanel userProcessContainer;
    private SalesPersonDirectory salesPersonDirectory;
    private MasterOrderCatalog moc;
    private CustomerCatalog customerCatalog;
    private SupplierDirectory supplierDirectory;
    public Reporting(JPanel userProcessContainer, SalesPersonDirectory salesPersonDirectory, MasterOrderCatalog moc, CustomerCatalog customerCatalog, SupplierDirectory supplierDirectory) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.salesPersonDirectory = salesPersonDirectory;
        this.moc = moc;
        this.customerCatalog = customerCatalog;
        this.supplierDirectory = supplierDirectory;
        populateTopProduct();
        bestCustomerByVolume();
        salespersonCombo.removeAllItems();
        for(SalesPerson sp : salesPersonDirectory.getSalesPersonList())
        {
            salespersonCombo.addItem(sp);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        mostPopularPrdTXTField = new javax.swing.JTextField();
        salespersonCombo = new javax.swing.JComboBox();
        jLabel3 = new javax.swing.JLabel();
        commissionTxtBox = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        mostPopularCustomerTXTField = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        aboveTarget = new javax.swing.JTextField();
        belowTarget = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();

        jLabel1.setText("Top 3 sales person by volume :");

        jLabel2.setText("Most popular product by sales volume :");

        salespersonCombo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel3.setText("Total commision paid for each Sales Person :");

        jLabel4.setText("Get customer with maximum products :");

        jButton1.setText("Generate Commisson");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel5.setText("Below Target");

        jLabel6.setText("Above Target");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(23, 23, 23)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel4)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(mostPopularCustomerTXTField, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel1)
                                            .addComponent(jLabel2)
                                            .addComponent(jLabel3))
                                        .addGap(60, 60, 60)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(mostPopularPrdTXTField, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addComponent(salespersonCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addGap(31, 31, 31))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel6))
                                .addGap(143, 143, 143)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(aboveTarget, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(commissionTxtBox, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(belowTarget, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(257, 257, 257)
                        .addComponent(jButton1)))
                .addContainerGap(131, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(mostPopularPrdTXTField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(mostPopularCustomerTXTField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(78, 78, 78)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(salespersonCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(commissionTxtBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jButton1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(aboveTarget, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(belowTarget, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addContainerGap(48, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
    double commission = 0.0;
        
        SalesPerson salesperson = (SalesPerson) salespersonCombo.getSelectedItem();
        int commAboveTarget = 0;
        int commBelowTarget = 0;
        for(Order o : moc.getOrderCatalog())
        {
        int size = o.getOrderItemList().size();
        
        for(int i=0;i<size;i++)
        {  
            OrderItem items = (OrderItem) o.getOrderItemList().get(i);
            if(o.getSalesPerson().equals(salesperson))
            {
                int salesPrice = o.fetchOrder(i);
                int target = items.getProduct().getTargetPrice();
                int quantity = items.getQuantity();
            
                if(salesPrice<=target)
                {
                    commission = commission+(salesPrice*0.10*quantity);
                    ++commBelowTarget;
                }
                else
                {
                    commission = commission+(salesPrice*0.15*quantity);
                    ++commAboveTarget;
                    
                }

            }   
          }
        }
        commissionTxtBox.setText(String.valueOf(commission));
        belowTarget.setText(String.valueOf(commBelowTarget));
        aboveTarget.setText(String.valueOf(commAboveTarget));
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField aboveTarget;
    private javax.swing.JTextField belowTarget;
    private javax.swing.JTextField commissionTxtBox;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField mostPopularCustomerTXTField;
    private javax.swing.JTextField mostPopularPrdTXTField;
    private javax.swing.JComboBox salespersonCombo;
    // End of variables declaration//GEN-END:variables

    private void populateTopProduct() {
        ArrayList<OrderItem> oItem=new ArrayList();
        for(Order o:moc.getOrderCatalog())
        {
        
        for(OrderItem oi:o.getOrderItemList())
        {
           
            Collections.sort(o.getOrderItemList());
            
            oItem.add(o.getOrderItemList().get(0));
           
        break;
        }
        
        }
      Collections.sort(oItem);
        
        mostPopularPrdTXTField.setText(String.valueOf(oItem.get(0).getProduct()));
        
                  
    
    } 

 

    private void bestCustomerByVolume() {
        Customer customerMaxProds = null;
        OrderItem newOi = null;
        String custName;
        
        ArrayList<OrderItem> oItem=new ArrayList();
        for(Order o:moc.getOrderCatalog())
        {
        
        for(OrderItem oi:o.getOrderItemList())
        {
           
            Collections.sort(o.getOrderItemList());
            
            oItem.add(o.getOrderItemList().get(0));
           
        break;
        }
        
        }
      Collections.sort(oItem);      
        
    for(Order o:moc.getOrderCatalog())
        {
        if(o.getOrderItemList().get(0).equals(oItem.get(0))){
            int custIDNew = o.getCustomer().getCustomerID();
            for(Customer cust : customerCatalog.getCustomerList()){
                if(cust.getCustomerID()==custIDNew)
            mostPopularCustomerTXTField.setText(cust.getFirstName());
            }
        }
            
        }
    }
}
