/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface;

import BusinessLogic.VitalSignHistory;

/**
 *
 * @author Piyush
 */
public class MainJFrame extends javax.swing.JFrame {

    /**
     * Creates new form MainJFrame
     */
    private VitalSignHistory vitalSignHistory;
    public MainJFrame() {
        initComponents();
        vitalSignHistory = new VitalSignHistory();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSplitPane1 = new javax.swing.JSplitPane();
        jSplitPane = new javax.swing.JPanel();
        CreateVSJButton = new javax.swing.JButton();
        ViewVSJButton = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        CreateVSJButton.setText("Create VS");
        CreateVSJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CreateVSJButtonActionPerformed(evt);
            }
        });

        ViewVSJButton.setText("View VS");
        ViewVSJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ViewVSJButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jSplitPaneLayout = new javax.swing.GroupLayout(jSplitPane);
        jSplitPane.setLayout(jSplitPaneLayout);
        jSplitPaneLayout.setHorizontalGroup(
            jSplitPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jSplitPaneLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jSplitPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(CreateVSJButton, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(ViewVSJButton, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap())
        );
        jSplitPaneLayout.setVerticalGroup(
            jSplitPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jSplitPaneLayout.createSequentialGroup()
                .addGap(72, 72, 72)
                .addComponent(CreateVSJButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 104, Short.MAX_VALUE)
                .addComponent(ViewVSJButton)
                .addGap(76, 76, 76))
        );

        jSplitPane1.setLeftComponent(jSplitPane);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 293, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 298, Short.MAX_VALUE)
        );

        jSplitPane1.setRightComponent(jPanel2);

        getContentPane().add(jSplitPane1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void CreateVSJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CreateVSJButtonActionPerformed
    CreateVitalSign cvs = new CreateVitalSign(vitalSignHistory);
    jSplitPane1.setRightComponent(cvs);
    }//GEN-LAST:event_CreateVSJButtonActionPerformed

    private void ViewVSJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ViewVSJButtonActionPerformed
    ViewVitalSign vvs = new ViewVitalSign(vitalSignHistory);
    jSplitPane1.setRightComponent(vvs);
    }//GEN-LAST:event_ViewVSJButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton CreateVSJButton;
    private javax.swing.JButton ViewVSJButton;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jSplitPane;
    private javax.swing.JSplitPane jSplitPane1;
    // End of variables declaration//GEN-END:variables
}
