/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.CarOwnerRole;

import Business.Car.Car;
import Business.CarOwner.CarOwner;
import Business.Enterprise.Enterprise;
import Business.Organization.CarOwnerOrganization;
import Business.Organization.Organization;
import Business.Organization.TravelSeekerOrganization;
import Business.TravelSeeker.TravelSeeker;
import Business.Traveller.Traveller;
import Business.UserAccount.UserAccount;
import Business.WorkQueue.CarPoolWorkRequest;
import Business.WorkQueue.CarUnlockWorkRequest;
import java.awt.CardLayout;
import java.awt.Component;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author Piyush
 */
public class ProcessWorkRequestSetStatusJPanel extends javax.swing.JPanel {

    /**
     * Creates new form ProcessWorkRequestSetStatusJPanel
     */
    JPanel userProcessContainer;
    CarUnlockWorkRequest request;
    UserAccount userAccount;
    Enterprise enterprise;
    public ProcessWorkRequestSetStatusJPanel(JPanel userProcessContainer, CarUnlockWorkRequest request, UserAccount userAccount, Enterprise enterprise) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.request = request;
        this.userAccount = userAccount;
        this.enterprise = enterprise;
        populateResultComboBox();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        backJButton = new javax.swing.JButton();
        submitJButton = new javax.swing.JButton();
        resultComboBox = new javax.swing.JComboBox();

        jLabel1.setText("Result");

        backJButton.setText("Back");
        backJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backJButtonActionPerformed(evt);
            }
        });

        submitJButton.setText("Submit Result");
        submitJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitJButtonActionPerformed(evt);
            }
        });

        resultComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(80, 80, 80)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(backJButton)))
                .addGap(188, 188, 188)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(submitJButton)
                    .addComponent(resultComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(40, 40, 40))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(resultComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(139, 139, 139)
                .addComponent(submitJButton)
                .addGap(22, 22, 22)
                .addComponent(backJButton)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void backJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backJButtonActionPerformed

        userProcessContainer.remove(this);
        Component[] componentArray = userProcessContainer.getComponents();
        Component component = componentArray[componentArray.length - 1];
        ProcessWorkRequestJPanel dwjp = (ProcessWorkRequestJPanel) component;
        dwjp.populateTable();
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_backJButtonActionPerformed

    private void submitJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitJButtonActionPerformed
        if(resultComboBox.getSelectedItem().equals("Accept")){
        request.setTestResult("Accepted");
        request.setStatus("Completed");
        
        Traveller tr = this.userAccount.getTraveller();
        CarOwner co = (CarOwner)tr;
        Car car = co.getCar();
        car.setCapacity(car.getCapacity()-1);
        
        Traveller t = request.getSender().getTraveller();
        TravelSeeker ts = (TravelSeeker)t;
        ts.setCar(car);
        
        Organization org = null;
        CarPoolWorkRequest requestCarPool = new CarPoolWorkRequest();
        requestCarPool.setReceiver(request.getSender());
        requestCarPool.setTravellerWithCar(t);
        
        for (Organization organization : enterprise.getOrganizationDirectory().getOrganizationList()){
            if (organization instanceof TravelSeekerOrganization){
                org = organization;
                break;
            }
        }
        if (org!=null){
            org.getWorkQueue().getWorkRequestList().add(requestCarPool);
        }
        JOptionPane.showMessageDialog(null, "You have successfully allowed the traveller " + t + " to unlock your car!");
        resultComboBox.setEnabled(false);
        }
        
        else{
            for(Organization org : enterprise.getOrganizationDirectory().getOrganizationList()){
                if(org instanceof CarOwnerOrganization){
                    org.getWorkQueue().getWorkRequestList().remove(request);
                }
            }
            UserAccount uaTravelSeeker = request.getSender();
            uaTravelSeeker.getWorkQueue().getWorkRequestList().remove(request);
            JOptionPane.showMessageDialog(null, "You have successfully rejected the traveller " + request.getSender().getTraveller() + " from unlock your car!");
            resultComboBox.setEnabled(false);
        }
        
    }//GEN-LAST:event_submitJButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backJButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JComboBox resultComboBox;
    private javax.swing.JButton submitJButton;
    // End of variables declaration//GEN-END:variables

    private void populateResultComboBox() {
        resultComboBox.removeAllItems();
        resultComboBox.addItem("Accept");
        resultComboBox.addItem("Remove");
    }

    

}
