/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.TravelSeekerRole;

import Business.Car.Car;
import Business.Enterprise.Enterprise;
import Business.Organization.CarOwnerOrganization;
import Business.Organization.Organization;
import static Business.Organization.Organization.Type.CarOwner;
import Business.Organization.TravelSeekerOrganization;
import Business.TravelSeeker.TravelSeeker;
import Business.Traveller.Traveller;
import Business.UserAccount.UserAccount;
import Business.WorkQueue.CarPoolWorkRequest;
import Business.WorkQueue.CarUnlockWorkRequest;
import UserInterface.CarOwnerRole.ProcessWorkRequestJPanel;
import java.awt.CardLayout;
import java.awt.Component;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author Piyush
 */
public class AddTravelSeekerToCarPoolSetStatusJPanel extends javax.swing.JPanel {

    /**
     * Creates new form AddTravelSeekerToCarPoolSetStatusJPanel
     */
    JPanel userProcessContainer;
    CarPoolWorkRequest request;
    UserAccount userAccount;
    Enterprise enterprise;
    public AddTravelSeekerToCarPoolSetStatusJPanel(JPanel userProcessContainer, CarPoolWorkRequest request, UserAccount userAccount, Enterprise enterprise) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.request = request;
        this.userAccount = userAccount;
        this.enterprise = enterprise;
        populateResultComboBox();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        backJButton = new javax.swing.JButton();
        submitJButton = new javax.swing.JButton();
        resultComboBox = new javax.swing.JComboBox();

        jLabel1.setText("Result");

        backJButton.setText("Back");
        backJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backJButtonActionPerformed(evt);
            }
        });

        submitJButton.setText("Submit Result");
        submitJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitJButtonActionPerformed(evt);
            }
        });

        resultComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(87, 87, 87)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(backJButton)))
                .addGap(104, 104, 104)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(resultComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(submitJButton))
                .addGap(40, 40, 40))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(67, 67, 67)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(resultComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(133, 133, 133)
                .addComponent(submitJButton)
                .addGap(15, 15, 15)
                .addComponent(backJButton)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void backJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backJButtonActionPerformed

        userProcessContainer.remove(this);
        Component[] componentArray = userProcessContainer.getComponents();
        Component component = componentArray[componentArray.length - 1];
        AddTravelSeekersToCarPoolJPanel dwjp = (AddTravelSeekersToCarPoolJPanel) component;
        dwjp.populateTable();
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_backJButtonActionPerformed

    private void submitJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitJButtonActionPerformed
        
        if(resultComboBox.getSelectedItem().equals("Accept")){
        request.setTestResult("Accepted");
        request.setStatus("Completed");

        Traveller tr = this.userAccount.getTraveller();
        TravelSeeker ts = (TravelSeeker)tr;
        Car car = ts.getCar();
        car.setCapacity(car.getCapacity()-1);

        Traveller t = request.getSender().getTraveller();
        TravelSeeker tSeeker = (TravelSeeker)t;
        tSeeker.setCar(car);
        JOptionPane.showMessageDialog(null, "You have successfully added the traveller " + t + " to car pool with you. Enjoy your ride!");
        resultComboBox.setEnabled(false);
        }
        else{
            UserAccount uaTravelSeeker = request.getSender();
            String travelSeekerName = String.valueOf(request.getSender().getTraveller());
            uaTravelSeeker.getWorkQueue().getWorkRequestList().remove(request);
            for(Organization org : enterprise.getOrganizationDirectory().getOrganizationList()){
                if(org instanceof TravelSeekerOrganization){
                    request.setMessage("");
                    request.setSender(null);
                    request.setStatus("");
                    request.setTestResult("");
                    request.setTravellerWithoutCar(null);
                    
                }
            }
            
            JOptionPane.showMessageDialog(null, "You have rejected the request from traveller " + travelSeekerName + " to car pool with you.");
            resultComboBox.setEnabled(false);
        }
    }//GEN-LAST:event_submitJButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backJButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JComboBox resultComboBox;
    private javax.swing.JButton submitJButton;
    // End of variables declaration//GEN-END:variables

    
    private void populateResultComboBox() {
        resultComboBox.removeAllItems();
        resultComboBox.addItem("Accept");
        resultComboBox.addItem("Remove");
    }

}
