/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.TravelSeekerRole;

import Business.Enterprise.Enterprise;
import Business.Organization.Organization;
import Business.Organization.TravelSeekerOrganization;
import Business.TravelSeeker.TravelSeeker;
import Business.Traveller.Traveller;
import Business.UserAccount.UserAccount;
import Business.WorkQueue.CarPoolWorkRequest;
import Business.WorkQueue.WorkRequest;
import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Piyush
 */
public class TravelSeekerCarPoolRequestSetMessageJPanel extends javax.swing.JPanel {

    /**
     * Creates new form TravelSeekerCarPoolRequestSetMessageJPanel
     */
    private JPanel userProcessContainer;
    private Enterprise enterprise;
    private UserAccount userAccount;
    private TravelSeeker travelSeeker;
    private TravelSeekerCarPoolJPanel dwjp;
    public TravelSeekerCarPoolRequestSetMessageJPanel(JPanel userProcessContainer, UserAccount userAccount, Enterprise enterprise, TravelSeeker travelSeeker,TravelSeekerCarPoolJPanel dwjp) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.enterprise = enterprise;
        this.userAccount = userAccount;
        this.travelSeeker = travelSeeker;
        this.dwjp = dwjp;
        populateRequestTable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        enterpriseLabel = new javax.swing.JLabel();
        valueLabel = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        messageJTextField = new javax.swing.JTextField();
        requestCarJButton = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        workRequestJTable = new javax.swing.JTable();
        backJButton = new javax.swing.JButton();

        enterpriseLabel.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        enterpriseLabel.setText("EnterPrise :");

        valueLabel.setText("<value>");

        jLabel1.setText("Message");

        requestCarJButton.setText("Request Car");
        requestCarJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                requestCarJButtonActionPerformed(evt);
            }
        });

        workRequestJTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Message", "Receiver", "Status", "Result"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(workRequestJTable);

        backJButton.setText("<<Back");
        backJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backJButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(requestCarJButton)
                .addGap(112, 112, 112))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(enterpriseLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(30, 30, 30)
                                .addComponent(valueLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(76, 76, 76)
                                .addComponent(jLabel1)
                                .addGap(42, 42, 42)
                                .addComponent(messageJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 612, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(backJButton)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(enterpriseLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(valueLabel)))
                .addGap(7, 7, 7)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(jLabel1))
                    .addComponent(messageJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(requestCarJButton)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(22, 22, 22)
                .addComponent(backJButton)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void requestCarJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_requestCarJButtonActionPerformed

        if(messageJTextField.getText().equals("")){
                    JOptionPane.showMessageDialog(null, "Enter the Message and then click here");
        }
        else {
        String message = messageJTextField.getText();
        int counter = 0;
        
                        
        Organization org = null;
        for (Organization organization : enterprise.getOrganizationDirectory().getOrganizationList()){
            if (organization instanceof TravelSeekerOrganization){
                org = organization;
                break;
            }
        }
        for (WorkRequest request : org.getWorkQueue().getWorkRequestList()){
            counter++;
                if(request.getReceiver().getTraveller().getName().equals(travelSeeker.getName()) && request.getSender()==null)
                {
                    CarPoolWorkRequest carPoolRequest = (CarPoolWorkRequest)request;
                    carPoolRequest.setMessage(message);
                    carPoolRequest.setSender(userAccount);
                    carPoolRequest.setTravellerWithoutCar(userAccount.getTraveller());
                    carPoolRequest.setStatus("Sent");
        
                    userAccount.getWorkQueue().getWorkRequestList().add(request);
                    break;
                }
                else if(request.getReceiver().getTraveller().getName().equals(travelSeeker.getName()) && request.getSender()!=null && org.getWorkQueue().getWorkRequestList().size()==counter){
                CarPoolWorkRequest carPoolRequest = new CarPoolWorkRequest();
                carPoolRequest.setMessage(message);
                carPoolRequest.setSender(userAccount);
                carPoolRequest.setTravellerWithoutCar(userAccount.getTraveller());
                carPoolRequest.setStatus("Sent");
                UserAccount userAccountFound = null;
                Traveller tr = (Traveller)travelSeeker;
                for(UserAccount ua : org.getUserAccountDirectory().getUserAccountList()){
                    if(ua.getTraveller()==tr){
                        userAccountFound = ua;
                    }
                }
                carPoolRequest.setReceiver(userAccountFound);
                carPoolRequest.setTravellerWithCar(tr);
                
                userAccount.getWorkQueue().getWorkRequestList().add(carPoolRequest);
                org.getWorkQueue().getWorkRequestList().add(carPoolRequest);
                break;
        }
                else if(request.getReceiver().getTraveller().getName().equals(travelSeeker.getName()) && request.getSender()!=null && org.getWorkQueue().getWorkRequestList().size()>counter){
                CarPoolWorkRequest carPoolRequest = new CarPoolWorkRequest();
                carPoolRequest.setMessage(message);
                carPoolRequest.setSender(userAccount);
                carPoolRequest.setTravellerWithoutCar(userAccount.getTraveller());
                carPoolRequest.setStatus("Sent");
                UserAccount userAccountFound = null;
                Traveller tr = (Traveller)travelSeeker;
                for(UserAccount ua : org.getUserAccountDirectory().getUserAccountList()){
                    if(ua.getTraveller()==tr){
                        userAccountFound = ua;
                    }
                }
                carPoolRequest.setReceiver(userAccountFound);
                carPoolRequest.setTravellerWithCar(tr);
                
                userAccount.getWorkQueue().getWorkRequestList().add(carPoolRequest);
                org.getWorkQueue().getWorkRequestList().add(carPoolRequest);
                break;
        }
        }
        populateRequestTable();
        }
    }//GEN-LAST:event_requestCarJButtonActionPerformed

    private void backJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backJButtonActionPerformed

        userProcessContainer.remove(this);
        dwjp.populateAvailableCarList();
        CardLayout layout = (CardLayout)userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_backJButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backJButton;
    private javax.swing.JLabel enterpriseLabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField messageJTextField;
    private javax.swing.JButton requestCarJButton;
    private javax.swing.JLabel valueLabel;
    private javax.swing.JTable workRequestJTable;
    // End of variables declaration//GEN-END:variables

    private void populateRequestTable() {
        DefaultTableModel model = (DefaultTableModel) workRequestJTable.getModel();
        model.setRowCount(0);
        for (WorkRequest request : userAccount.getWorkQueue().getWorkRequestList()){
            if(request instanceof CarPoolWorkRequest){
                if(request.getSender()==this.userAccount){
            Object[] row = new Object[4];
            row[0] = request.getMessage();
            row[1] = request.getReceiver();
            row[2] = request.getStatus();
            String result = ((CarPoolWorkRequest) request).getTestResult();
            row[3] = result == null ? "Waiting" : result;
            
            model.addRow(row);
            }
        }
        }
        }
    }
    


