/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.TravelSeekerRole;

import Business.EcoSystem;
import Business.Enterprise.Enterprise;
import Business.Network.Location;
import Business.Network.Network;
import Business.Organization.TravelSeekerOrganization;
import Business.TravelSeeker.TravelSeeker;
import Business.UserAccount.UserAccount;
import FieldLevelValidation.FieldLevelValidation;
import java.awt.CardLayout;
import java.awt.Component;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author Piyush
 */
public class TravelSeekerDetailsJPanel extends javax.swing.JPanel {

    /**
     * Creates new form TravelSeekerJPanel
     */
    private JPanel userProcessContainer;
    private TravelSeekerOrganization organization;
    private Enterprise enterprise;
    private UserAccount userAccount;
    public TravelSeekerDetailsJPanel(JPanel userProcessContainer, UserAccount userAccount, TravelSeekerOrganization organization, Enterprise enterprise) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.organization = organization;
        this.enterprise = enterprise;
        this.userAccount = userAccount;
        
        travellerNameTextField.setText(userAccount.getTraveller().getName());
        
        populateCarAvailableFromComboBox();
        populateCarAvailableUntilComboBox();
        populateAllFields();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        travellerNameTextField = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        submitCarBTN = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        backJButton = new javax.swing.JButton();
        travellerCurrentLocationTXTField = new javax.swing.JTextField();
        travellerDestinationLocationTXTField = new javax.swing.JTextField();
        carAvailableFromComboBox = new javax.swing.JComboBox();
        carAvailableUntilComboBox = new javax.swing.JComboBox();

        jLabel1.setText("Name : ");

        travellerNameTextField.setEnabled(false);

        jLabel4.setText("Car Needed From : ");

        jLabel5.setText("Car Needed Until : ");

        jLabel3.setText("Traveller Location : ");

        submitCarBTN.setText("Submit");
        submitCarBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitCarBTNActionPerformed(evt);
            }
        });

        jLabel6.setText("Destination Location : ");

        backJButton.setText("<< Back");
        backJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backJButtonActionPerformed(evt);
            }
        });

        carAvailableFromComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        carAvailableFromComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                carAvailableFromComboBoxActionPerformed(evt);
            }
        });

        carAvailableUntilComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        carAvailableUntilComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                carAvailableUntilComboBoxActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(61, 61, 61)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addComponent(jLabel3)
                            .addComponent(jLabel1)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5))
                        .addGap(78, 78, 78)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(travellerNameTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 90, Short.MAX_VALUE)
                            .addComponent(travellerCurrentLocationTXTField, javax.swing.GroupLayout.DEFAULT_SIZE, 90, Short.MAX_VALUE)
                            .addComponent(travellerDestinationLocationTXTField, javax.swing.GroupLayout.DEFAULT_SIZE, 90, Short.MAX_VALUE)
                            .addComponent(carAvailableFromComboBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(carAvailableUntilComboBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(165, 165, 165)
                        .addComponent(submitCarBTN))
                    .addComponent(backJButton))
                .addGap(89, 89, 89))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(travellerNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(travellerCurrentLocationTXTField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(travellerDestinationLocationTXTField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(carAvailableFromComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(carAvailableUntilComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addGap(10, 10, 10)
                .addComponent(submitCarBTN)
                .addGap(21, 21, 21)
                .addComponent(backJButton)
                .addGap(20, 20, 20))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void submitCarBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitCarBTNActionPerformed

        FieldLevelValidation flv = new FieldLevelValidation();
        
        String availableFromString = (String)carAvailableFromComboBox.getSelectedItem();
        int indexOfColonInFrom = availableFromString.indexOf(":");
        int availableFrom = Integer.parseInt(availableFromString.substring(0,indexOfColonInFrom).trim());
        
        String availableUntilString = (String)carAvailableUntilComboBox.getSelectedItem();
        int indexOfColonInUntil = availableUntilString.indexOf(":");
        int availableUntil = Integer.parseInt(availableUntilString.substring(0,indexOfColonInUntil).trim());
        
        if(travellerCurrentLocationTXTField.getText().equals("") || travellerDestinationLocationTXTField.getText().equals("") ){
            JOptionPane.showMessageDialog(null, "One or more fields are blank!");
        }
        
        else if(availableFromString.equals(availableUntilString)){
            JOptionPane.showMessageDialog(null, "Car needed from and until are same. Cannot Save.");
        }
        
        else if(availableFrom>availableUntil){
            JOptionPane.showMessageDialog(null, "The until date is greater than the from date. Cannot save.");
        }
        
        else if((availableUntil - availableFrom) > 8){
            JOptionPane.showMessageDialog(null, "You cannot unlock a car beyond 8 hours.");
        }
        
        else if(!flv.validateLocationField(travellerCurrentLocationTXTField.getText())){
            JOptionPane.showMessageDialog(null, "Invalid Traveller Current Location. Please Enter The Complete Address.");
        }  
        
        else if(!flv.validateLocationField(travellerDestinationLocationTXTField.getText())){
            JOptionPane.showMessageDialog(null, "Invalid Destination Address. Please Enter The Complete Address.");
        }
        
        else{
        TravelSeeker ts = (TravelSeeker)userAccount.getTraveller();
            ts.setCarNeededFrom(availableFrom);
            ts.setCarNeededUntil(availableUntil);
            ts.setLocation(travellerCurrentLocationTXTField.getText());
            ts.setDestinationLocation(travellerDestinationLocationTXTField.getText());
            JOptionPane.showMessageDialog(null, "Added Successfully!");
        }
        
        
    }//GEN-LAST:event_submitCarBTNActionPerformed

    private void backJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backJButtonActionPerformed
        userProcessContainer.remove(this);
        Component[] componentArray = userProcessContainer.getComponents();
        Component component = componentArray[componentArray.length - 1];
        TravelSeekerWorkAreaJPanel dwjp = (TravelSeekerWorkAreaJPanel) component;
        dwjp.disableButtonLogic();
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_backJButtonActionPerformed

    private void carAvailableFromComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_carAvailableFromComboBoxActionPerformed
        
    }//GEN-LAST:event_carAvailableFromComboBoxActionPerformed

    private void carAvailableUntilComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_carAvailableUntilComboBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_carAvailableUntilComboBoxActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backJButton;
    private javax.swing.JComboBox carAvailableFromComboBox;
    private javax.swing.JComboBox carAvailableUntilComboBox;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JButton submitCarBTN;
    private javax.swing.JTextField travellerCurrentLocationTXTField;
    private javax.swing.JTextField travellerDestinationLocationTXTField;
    private javax.swing.JTextField travellerNameTextField;
    // End of variables declaration//GEN-END:variables


    public void populateAllFields() {
        TravelSeeker ts = (TravelSeeker)userAccount.getTraveller();
        if(ts.getLocation()!=null){
        carAvailableFromComboBox.removeAllItems();
        carAvailableUntilComboBox.removeAllItems();
        carAvailableFromComboBox.addItem(String.valueOf(ts.getCarNeededFrom()) + ":00");
        carAvailableUntilComboBox.addItem(String.valueOf(ts.getCarNeededUntil()) + ":00");
        travellerCurrentLocationTXTField.setText(ts.getLocation());
        travellerDestinationLocationTXTField.setText(ts.getDestinationLocation());
        }
    }
        private void populateCarAvailableFromComboBox() {
        carAvailableFromComboBox.removeAllItems();
        String[] availableFrom = {"1:00","2:00","3:00","4:00","5:00","6:00","7:00","8:00","9:00","10:00",
                                    "11:00","12:00","13:00","14:00","15:00","16:00","17:00","18:00","19:00","20:00",
                                    "21:00","22:00","23:00","24:00"};
        for(String timeValue : availableFrom){
        carAvailableFromComboBox.addItem(timeValue);
        }
    }
    
    private void populateCarAvailableUntilComboBox() {
        carAvailableUntilComboBox.removeAllItems();
        String[] availableUntil = {"1:00","2:00","3:00","4:00","5:00","6:00","7:00","8:00","9:00","10:00",
                                    "11:00","12:00","13:00","14:00","15:00","16:00","17:00","18:00","19:00","20:00",
                                    "21:00","22:00","23:00","24:00"};
        for(String timeValue : availableUntil){
        carAvailableUntilComboBox.addItem(timeValue);
        }
    }
}
